-- Fichas técnicas de cada producto (tal como las entregó el cliente)

INSERT INTO product_specs (product_id, label, value, display_order)
SELECT p.id, s.label, s.value, s.ord
FROM (VALUES
-- Carpetas Institucionales
('carpetas-institucionales', 'Material', 'Cartulina ilustración', 1),
('carpetas-institucionales', 'Formato', 'A4 / personalizado', 2),
('carpetas-institucionales', 'Impresión', 'Full color', 3),
('carpetas-institucionales', 'Cantidad mínima offset', '250 unidades', 4),
('carpetas-institucionales', 'Terminaciones', 'OPP mate/brillante, UV sectorizado', 5),
('carpetas-institucionales', 'Configuración', 'Con solapa', 6),
-- Tarjetas personales / empresariales
('tarjetas-personales-empresariales', 'Material', 'Papel ilustración 350gr', 1),
('tarjetas-personales-empresariales', 'Formato', '8,5 × 5 cm o medida personalizada', 2),
('tarjetas-personales-empresariales', 'Impresión', 'Frente y dorso, full color', 3),
('tarjetas-personales-empresariales', 'Cantidad mínima', '500 unidades', 4),
('tarjetas-personales-empresariales', 'Terminaciones', 'OPP mate o brillante, UV sectorizado, cuño en seco, redondeado de puntas', 5),
('tarjetas-personales-empresariales', 'Personalización', 'Diseño totalmente personalizado según la identidad de la empresa o profesional', 6),
-- Sobres personalizados
('sobres-personalizados', 'Material', 'Papel obra 90gr', 1),
('sobres-personalizados', 'Formato', 'Oficio, A4, carta o medida personalizada', 2),
('sobres-personalizados', 'Impresión', 'Frente y dorso, full color', 3),
('sobres-personalizados', 'Cantidad mínima', '500 unidades', 4),
('sobres-personalizados', 'Personalización', 'Logo, datos de contacto, colores y diseño adaptado a la identidad de la empresa', 5),
-- Anotadores corporativos
('anotadores-corporativos', 'Material', 'Papel obra 80gr, base de cartulina', 1),
('anotadores-corporativos', 'Formato', 'A5, A6 o medida personalizada', 2),
('anotadores-corporativos', 'Impresión', 'Hojas impresas full color, frente o frente y dorso', 3),
('anotadores-corporativos', 'Cantidad mínima offset', 'Según cantidad de páginas y tamaño', 4),
('anotadores-corporativos', 'Encuadernación', 'Enblocado', 5),
('anotadores-corporativos', 'Personalización', 'Logo y colores adaptados a la identidad de la empresa', 6),
-- Folletos
('folletos', 'Material', 'Papel ilustración u obra', 1),
('folletos', 'Formato', 'A4, A5, A6 o medida personalizada', 2),
('folletos', 'Impresión', 'Full color, simple o doble faz', 3),
('folletos', 'Cantidad mínima offset', 'Según formato y cantidad', 4),
('folletos', 'Tipos', 'Simples, dípticos, trípticos, cuadrípticos o plegados especiales', 5),
('folletos', 'Terminaciones', 'Plegado', 6),
('folletos', 'Personalización', 'Diseño, formato, cantidad de cuerpos y terminaciones adaptadas a cada necesidad', 7),
-- Catálogos
('catalogos', 'Material', 'Papel ilustración u obra', 1),
('catalogos', 'Formato', 'A4, A5, cuadrado o medida personalizada', 2),
('catalogos', 'Impresión', 'Full color', 3),
('catalogos', 'Cantidad mínima offset', 'Según formato y cantidad de páginas', 4),
('catalogos', 'Terminaciones', 'OPP mate o brillante, UV sectorizado, hot stamping y terminaciones especiales', 5),
('catalogos', 'Encuadernación', 'Abrochado, cosido o anillado', 6),
('catalogos', 'Personalización', 'Formato, cantidad de páginas, diseño, papel y terminaciones adaptadas a cada catálogo', 7),
-- Individuales personalizados
('individuales-personalizados', 'Material', 'Papel obra, ilustración, cartulina u otros materiales según el uso', 1),
('individuales-personalizados', 'Formato', '42 × 30 cm, 45 × 30 cm o medida personalizada', 2),
('individuales-personalizados', 'Impresión', 'Full color, simple faz', 3),
('individuales-personalizados', 'Cantidad mínima offset', '2000 unidades', 4),
('individuales-personalizados', 'Presentación', 'Individual suelto, promocional, gastronómico o personalizado', 5),
('individuales-personalizados', 'Personalización', 'Logo, colores, menú, promociones, QR, juegos o diseño adaptado a cada marca', 6),
-- Libros
('libros', 'Material', 'Papel obra o ilustración', 1),
('libros', 'Formato', 'A4, A5 o medida personalizada', 2),
('libros', 'Impresión', 'Interior en blanco y negro o full color; tapa a color', 3),
('libros', 'Cantidad mínima offset', 'Según cantidad de páginas y formato', 4),
('libros', 'Terminaciones', 'OPP mate o brillante, barniz UV o UV sectorizado', 5),
('libros', 'Encuadernación', 'Cosido, abrochado o fresado', 6),
-- Revistas
('revistas', 'Material', 'Papel ilustración u obra', 1),
('revistas', 'Formato', 'A4, A5, A6 o medida personalizada', 2),
('revistas', 'Impresión', 'Blanco y negro o full color', 3),
('revistas', 'Cantidad mínima offset', 'Según cantidad de páginas y formato', 4),
('revistas', 'Terminaciones', 'OPP mate o brillante, o barniz UV', 5),
('revistas', 'Encuadernación', 'Abrochado', 6),
('revistas', 'Personalización', 'Formato, cantidad de páginas, papel y terminaciones adaptadas a cada publicación', 7),
-- Cómics
('comics', 'Material', 'Papel ilustración u obra', 1),
('comics', 'Formato', 'A4, A5, 17 × 24 cm o medida personalizada', 2),
('comics', 'Impresión', 'Interior y tapa en blanco y negro o full color', 3),
('comics', 'Cantidad mínima offset', 'Según cantidad de páginas y formato', 4),
('comics', 'Terminaciones', 'OPP mate o brillante, UV sectorizado o barniz UV', 5),
('comics', 'Encuadernación', 'Abrochado, cosido o fresado', 6),
('comics', 'Personalización', 'Formato, cantidad de páginas, papel, tapa, diseño y terminaciones a medida', 7),
-- Manuales / Instructivos
('manuales-instructivos', 'Material', 'Papel obra o ilustración', 1),
('manuales-instructivos', 'Formato', 'A4, A5 o medida personalizada', 2),
('manuales-instructivos', 'Impresión', 'Blanco y negro o full color, simple o doble faz', 3),
('manuales-instructivos', 'Cantidad mínima offset', 'Según cantidad de páginas y formato', 4),
('manuales-instructivos', 'Terminaciones', 'Según proyecto', 5),
('manuales-instructivos', 'Encuadernación', 'Abrochado', 6),
('manuales-instructivos', 'Personalización', 'Formato, cantidad de páginas, tapa e interiores adaptados a cada empresa', 7),
-- Talonarios
('talonarios', 'Material', 'Papel obra', 1),
('talonarios', 'Formato', 'A4, A5, A6 o medida personalizada', 2),
('talonarios', 'Impresión', '1 o más tintas, simple o doble faz', 3),
('talonarios', 'Cantidad mínima offset', 'Según formato, cantidad de juegos y tirada', 4),
('talonarios', 'Numeración', 'Correlativa y personalizada', 5),
('talonarios', 'Terminaciones', 'Puntillado y encolado', 6),
('talonarios', 'Presentación', 'En blocks, juegos autocopiativos o talonarios individuales', 7),
('talonarios', 'Personalización', 'Logo, datos de empresa, campos, numeración y diseño adaptado a cada necesidad', 8),
-- Remitos
('remitos', 'Material', 'Papel obra', 1),
('remitos', 'Formato', 'A4, A5, A6 o medida personalizada', 2),
('remitos', 'Impresión', '1 o más tintas, simple o doble faz', 3),
('remitos', 'Cantidad mínima offset', 'Según formato, cantidad de juegos y tirada', 4),
('remitos', 'Numeración', 'Correlativa y personalizada', 5),
('remitos', 'Terminaciones', 'Puntillado y encolado', 6),
('remitos', 'Presentación', 'En blocks o juegos autocopiativos', 7),
('remitos', 'Personalización', 'Logo, datos de empresa, campos, numeración y diseño adaptado a cada necesidad', 8),
-- Rifas
('rifas', 'Material', 'Papel obra, ilustración o cartulina según el diseño', 1),
('rifas', 'Formato', 'Medida personalizada', 2),
('rifas', 'Impresión', 'Full color, simple o doble faz', 3),
('rifas', 'Cantidad mínima offset', 'Según formato', 4),
('rifas', 'Numeración', 'Correlativa y personalizada', 5),
('rifas', 'Terminaciones', 'Puntillado, perforado, troquelado y terminaciones especiales', 6),
('rifas', 'Presentación', 'Con talón desprendible o formato simple', 7),
('rifas', 'Personalización', 'Logo, datos del sorteo, premios, fecha, numeración y diseño adaptado a cada evento', 8),
-- Entradas
('entradas', 'Material', 'Papel obra, ilustración o cartulina según el diseño', 1),
('entradas', 'Formato', 'Medida personalizada', 2),
('entradas', 'Impresión', 'Full color + tintas especiales, simple o doble faz', 3),
('entradas', 'Cantidad mínima offset', 'Según tamaño', 4),
('entradas', 'Numeración', 'Correlativa y personalizada', 5),
('entradas', 'Terminaciones', 'Puntillado y troquelado', 6),
('entradas', 'Presentación', 'Con talón desprendible o formato simple', 7),
('entradas', 'Personalización', 'Logo, fecha, sector, ubicación, numeración, QR y diseño adaptado a cada evento', 8),
-- Estuches
('estuches', 'Material', 'Cartulina', 1),
('estuches', 'Formato', 'Medida totalmente personalizada', 2),
('estuches', 'Impresión', 'Full color', 3),
('estuches', 'Cantidad mínima offset', 'Según formato y material', 4),
('estuches', 'Terminaciones', 'OPP mate o brillante, barniz UV, UV sectorizado, hot stamping, cuño en seco', 5),
('estuches', 'Troquelado', 'Estructuras personalizadas', 6),
('estuches', 'Presentación', 'Plegados, pegados o entregados planos según necesidad', 7),
('estuches', 'Personalización', 'Diseño, medidas, colores, identidad de marca y estructura adaptada a cada producto', 8),
-- Etiquetas autoadhesivas
('etiquetas-autoadhesivas', 'Material', 'Papel autoadhesivo', 1),
('etiquetas-autoadhesivas', 'Formato', 'Rectangular, circular, ovalado o medida personalizada', 2),
('etiquetas-autoadhesivas', 'Impresión', 'Full color', 3),
('etiquetas-autoadhesivas', 'Cantidad mínima offset', 'Según formato y tirada', 4),
('etiquetas-autoadhesivas', 'Terminaciones', 'Barniz UV', 5),
('etiquetas-autoadhesivas', 'Presentación', 'En pliegos o formatos personalizados', 6),
('etiquetas-autoadhesivas', 'Personalización', 'Logo, colores, información del producto, códigos, QR y diseño adaptado a cada marca', 7),
-- Cajas para delivery
('cajas-para-delivery', 'Material', 'Cartulina o cartón microcorrugado', 1),
('cajas-para-delivery', 'Formato', 'Medidas personalizadas', 2),
('cajas-para-delivery', 'Impresión', '1 o más tintas / full color', 3),
('cajas-para-delivery', 'Cantidad mínima offset', 'Según formato, material y tirada', 4),
('cajas-para-delivery', 'Terminaciones', 'Troquelado', 5),
('cajas-para-delivery', 'Personalización', 'Logo, colores, diseño, mensajes, QR y medidas adaptadas a cada marca', 6),
-- Collarines y Cenefas de góndola
('collarines-cenefas-gondola', 'Material', 'Cartulina, papel ilustración u otros materiales según el uso', 1),
('collarines-cenefas-gondola', 'Formato', 'Medida estándar o personalizada', 2),
('collarines-cenefas-gondola', 'Impresión', 'Full color, simple o doble faz', 3),
('collarines-cenefas-gondola', 'Cantidad mínima offset', 'Según formato y tirada', 4),
('collarines-cenefas-gondola', 'Terminaciones', 'OPP mate o brillante, barniz UV, troquelado y terminaciones especiales', 5),
('collarines-cenefas-gondola', 'Troquelado', 'Formas y encastres personalizados según el producto o exhibidor', 6),
('collarines-cenefas-gondola', 'Presentación', 'Sueltos, troquelados o listos para colocar', 7),
('collarines-cenefas-gondola', 'Personalización', 'Logo, colores, promociones, mensajes y diseño adaptado a cada marca', 8),
-- Naipes personalizados
('naipes-personalizados', 'Material', 'Cartulina ilustración u otros materiales según el proyecto', 1),
('naipes-personalizados', 'Formato', 'Baraja española o medida personalizada', 2),
('naipes-personalizados', 'Impresión', 'Full color, frente y dorso', 3),
('naipes-personalizados', 'Cantidad mínima offset', 'Según formato', 4),
('naipes-personalizados', 'Terminaciones', 'OPP mate o brillante, barniz UV, UV sectorizado, redondeado de puntas', 5),
('naipes-personalizados', 'Presentación', 'Con caja personalizada', 6),
('naipes-personalizados', 'Personalización', 'Diseño de dorso, estuche, colores, logos y detalles adaptados a cada marca', 7),
-- Cuadernos personalizados
('cuadernos-personalizados', 'Material', 'Tapas en cartulina, interiores en papel obra', 1),
('cuadernos-personalizados', 'Formato', 'A4, A5, A6 o medida personalizada', 2),
('cuadernos-personalizados', 'Impresión', 'Tapa personalizada e interiores lisos, rayados, cuadriculados o impresos', 3),
('cuadernos-personalizados', 'Cantidad mínima offset', 'Según formato, cantidad de páginas y diseño', 4),
('cuadernos-personalizados', 'Terminaciones', 'OPP mate o brillante, UV sectorizado, hot stamping', 5),
('cuadernos-personalizados', 'Encuadernación', 'Anillado', 6),
('cuadernos-personalizados', 'Personalización', 'Logo, colores, diseño de tapa e interiores adaptados a la identidad de cada empresa', 7),
-- Calendarios personalizados
('calendarios-personalizados', 'Material', 'Papel ilustración o cartulina', 1),
('calendarios-personalizados', 'Formato', 'De pared, de escritorio, de bolsillo o medida personalizada', 2),
('calendarios-personalizados', 'Impresión', 'Full color, simple o doble faz según el diseño', 3),
('calendarios-personalizados', 'Cantidad mínima offset', 'Según formato y modelo', 4),
('calendarios-personalizados', 'Terminaciones', 'Terminaciones especiales', 5),
('calendarios-personalizados', 'Presentación', 'De pared, sobremesa, tríptico, de bolsillo u otros formatos', 6),
('calendarios-personalizados', 'Personalización', 'Logo, colores, imágenes, fechas especiales y diseño adaptado a cada empresa', 7),
-- Almanaques personalizados
('almanaques-personalizados', 'Material', 'Papel ilustración o cartulina', 1),
('almanaques-personalizados', 'Formato', 'De pared, bolsillo o medida personalizada', 2),
('almanaques-personalizados', 'Impresión', 'Full color, simple faz', 3),
('almanaques-personalizados', 'Cantidad mínima offset', 'Según formato y diseño', 4),
('almanaques-personalizados', 'Terminaciones', 'OPP mate o brillante, perforado y terminaciones especiales', 5),
('almanaques-personalizados', 'Presentación', 'Diseño personalizado', 6),
('almanaques-personalizados', 'Personalización', 'Logo, colores, imágenes, datos de contacto y diseño adaptado a cada empresa', 7)
) AS s(product_slug, label, value, ord)
JOIN products p ON p.slug = s.product_slug;
